typography_spectrum: 0.6385080742184073
color:
  brandStrength: 0.29466053401120007
  lightness: 0.6649795768316835
  saturation: 0.6348967328667641
  rhythmicContrast: 0.20808787876740098
  brandColors:
    - '#222222'
    - '#EEEEEE'
    - '#F0C331'
    - '#5D6471'
    - '#888D96'
layout_spectrum: 0.2436345205642283
author:
  name: Rafael Nep么
  email: rafaelncosta@gmail.com
  url: www.rafaelnepo.com
name: Canal do Nep么
navigation:
  - name: Rafael Nep么
    url: www.rafaelnepo.com
    type: external
title: 'Oi, eu sou o Nep么!'
description: 'Games, Design & Education'
