typography_spectrum: 0.2923720027320087
color:
  brandStrength: 0.3276069366838783
  lightness: 0.8202438615262508
  saturation: 0.9489243566058576
  rhythmicContrast: 0.1374031773302704
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
layout_spectrum: 0.3841551151126623
author:
  name: Rafael Nepô
  email: rafaelncosta@gmail.com
  url: www.rafaelnepo.com
name: Canal do Nepô
title: 'Oi, eu sou o Nepô!'
description: 'Games, Design & Education'
